### PR TITLE
[feature] Install Python requirements in base image

### PR DESCRIPTION
**Pull request by stumpylog**
Ok, last one for a bit, I promise.

This adds the rest of the python dependencies to the base image.  it looks to shave a few more minutes off building the primary repo's image: https://github.com/paperless-ngx/paperless-ngx/runs/5874373556?check_suite_focus=true.  I think the bulk of the time now comes from building the frontend.

The main repo image will still install from requirement.txt, but find the requirements [already satisfied](https://github.com/paperless-ngx/paperless-ngx/runs/5874373556?check_suite_focus=true#step:7:2822)

### How it works
1. Check if paperless-ngx repo has a matching branch to the pipeline triggering branch
2. If yes, use that branch
3. If no, use paperless-ngx repo `dev`
4. Clone the paperless-ngx repo at the given branch
5. Elide the requirements this builder produces (this ensures the version doesn't go backwards)
6. Install from requirements.txt

- If the base image includes awesomelib==1.0.0, but the main image installs awesomelib==2.0.0, the library is replaced, but the size of awesomelib 1.0.0 will still exist in the container
- If the main image needs othercoolthing==1.0.0, but it isn't in the base image, it will just be installed
- If the main image removes nosocoolthing==2.0.0, it might still be in the base for a bit until a rebuild happens

### CODE REVIEW

**Review by qcasey — APPROVED** [review]
Great!

**Comment by qcasey** [comment]
I'm very curious to see this working in practice.

**Comment by shamoon** [comment]
Yea this also sounds very useful, just want to document. Is this still accurate https://github.com/paperless-ngx/builder#setting-dependency-versions / https://github.com/paperless-ngx/builder#adding-new-dependency ?

And maybe im overthinking it but now Im wondering what the purpose of dependabot is on the main repo (for python packages)? Like could we just only let it work here but every time we update a package here we secondarily update in main repo?

**Comment by stumpylog** [comment]
Yes, both those are still valid for adding a new dependency where we can't rely on an existing, pre-compiled version.  For basically everything except the 2 Python libraries we build here, there's already an existing and working version we can simply download.

Ideally at some point, we can determine a way to combine this back to the main repo, so there isn't any sharing files.  It could probably be done with multiple workflows, triggering each other, on certain file pattern updates.  Or something.  But for now, I think this is a good solution.

**Comment by shamoon** [comment]
Thanks. What about the dependabot on the main repo question, could we just use it here and either manually for now or automatically have that push the change to main repo _after_ its been merged here? Or maybe that doesnt work.

Yea it would be great to get this back into main some day so we're not having to maintain the same stuff in two places but this is really awesome for now!

**Comment by qcasey** [comment]
It's my understanding that the only deps dependabot manages here in the `builder` repo are the ones being built from source. All the other deps we can preinstall from the `main` repo would be bumped over there.

Put a different way, this PR clones the `requirements.txt` from our main repo when building the image. The majority of deps would still be managed in that file. So dependabot is still wanted in both repos.

I think that's correct anyway.

**Comment by shamoon** [comment]
Ohhhh that makes a lot more sense. Thanks!

**Pull request merged**
