### PR TITLE
Use dependabot for Python versioning

### PR DESCRIPTION
**Pull request by stumpylog**
Instead of needing to hand modify the `pipeline.yml` file for every Python version, now we can make dependabot work for us!

This update adds a Pipfile and the associated lock file.  Now, all version information for Python packages is read from the Pipfile.lock, which dependabot will help us keep updated.  For non-Python, the configuration is now a simple update to the Python script which generates the build information.  Even better, when dependabot creates its branch, the images will be built and tagged, so the merge to main can use the existing tags, instead of re-building again.

The setup is what really changed.  Now the workflow calls a Python script, which outputs a JSON object of the details for the given package.  That JSON is passed around as needed to all other jobs.

### CODE REVIEW

**Comment by shamoon** [comment]
Also, when theres a dependency bump here and we merge it does the version here get bumped, and then we have to update https://github.com/paperless-ngx/paperless-ngx/blob/2d850795d8e5289220f92ed7936267d0c8d3d6a2/Dockerfile#L9 to use that new version?

**Comment by stumpylog** [comment]
That's the idea, at least for Python packages which are built here.  qpdf isn't automated, but a pikepdf update might tell us if there's a new version to try and build.  Otherwise, I don't think Debian package updates are exactly swift.  Then jbig2enc hasn't seen an update in many, many years, so I doubt it will ever again.  But in both those cases, the version can now be set in a single location, which anyone can do, with the changes flowing magically into the actions.

Hopefully the docs still make sense.  It's always hard to make sure everyone can understand them without needing to examine actual code too much.

I tried to cover in the README how versions would work.  Let me re-state it differently and then it can get updated there if it's better.

1. When a new dep is merged in here, a tag should be created with the patch updated
2. This triggers a new build of `:latest`, `major.minor.patch` and `major.minor`
3. The dep is merged into the main repo
4. The main repo depends on `major.minor`, so it pulls the newly built base image with the new dep installed
5. At release time, the main repo is locked to a `major.minor.patch`, unless we need to update a dep to fix something.  This prevents future build of the image from pulling in a new dep

Putting names and numbers in:
1. `pikepdf` releases 5.1.1
2. dependabot tells us here and on the main repo about the new version
3. 5.1.1 is merged into this repo
4. This repo is tagged as 1.0.2
5. The repo builds `:latest`, `:1.0.2` and `:1.0`
6. 5.1.1 is merged into main repo
7. main repo builds image using the just built `:1.0`
8. We're releasing ngx-1.7.0, the beta branch is set to use `:1.0.2` with the particular versions built into that

At least that's how it works in my head.  If there's a better, easier way to do it or explain it, I'm all ears.

**Comment by qcasey** [comment]
This is excellent!

> Putting names and numbers in:
> 
>     1. `pikepdf` releases 5.1.1
> 
>     2. dependabot tells us here and on the main repo about the new version
> 
>     3. 5.1.1 is merged into this repo
> 
>     4. This repo is tagged as 1.0.2
> 
>     5. The repo builds `:latest`, `:1.0.2` and `:1.0`
> 
>     6. 5.1.1 is merged into main repo
> 
>     7. main repo builds image using the just built `:1.0`
> 
>     8. We're releasing ngx-1.7.0, the beta branch is set to use `:1.0.2` with the particular versions built into that

This example really helped me understand the process, I think we should include it as an "Overview" in the docs.

**Comment by stumpylog** [comment]
Actually, what about this:

1. main repo `dev` uses `:dev` tag of this repo.  Which is rebuilt with every dep update here, then used when the dep is merged to main
2. At release time, this repo is tagged to match the main repo release version
3. main repo release branch (and eventually main) updated to the base tagged version
4. dep updates continue to get merged into main

Again with some numbers:

1. pikepdf release 5.1.2
2. dependabot tells us here and on the main repo about the new version
3. 5.1.2 is merged into this repo, repo builds `:dev`
4. We're releasing 1.7.0, create branch `beta-1.7.0` in main 
5. Merge builder `dev` to builder `main` and tag this repo with it's current deps as 1.7.0
6. Update Dockerfile in `beta-1.7.0` to use base image `:1.7.0`
7. Release is ready, merged to main's main branch

That seems simpler to reason about, as it keeps versions and names matching better across the two repos.  I'd better make some diagrams.

**Comment by shamoon** [comment]
> This example really helped me understand the process, I think we should include it as an "Overview" in the docs.

Yes, totally this is great. Perhaps that example should go into the org-docs (which btw I just made into one readme file), which currently has a section that links to this readme =)

**Comment by shamoon** [comment]
Yea that sounds like a good idea, make the versions match, -ngx v1.7.0 <--> builder v1.7.0

In between your step 3 /4, do we merge pikepdf 5.1.2 into -ngx dev too?

**Comment by stumpylog** [comment]
> In between your step 3 /4, do we merge pikepdf 5.1.2 into -ngx dev too?

See, even I'm missing a step.  Yes, that would need to happen.

**Comment by shamoon** [comment]
Haha, thats why I want to write it all down 😅

**Comment by shamoon** [comment]
See https://github.com/paperless-ngx/org-docs/blob/main/README.md#example-base-image-process-for-release for now

**Comment by shamoon** [comment]
One thing Im still not 100% on is the purpose of `dev` here. When we update a dependency and it gets merged into dev, why not just directly merge to main? We have the tags to "pin" the releases, e.g. -ngx `v1.7.0` will always use `builder@1.7.0` so we dont have to worry about `main` here being ahead of the current release.

**Comment by shamoon** [comment]
Sorry for the 1 million questions. Also, the step "Update Dockerfile in `beta-1.7.0` to use base image `:1.7.0`", should that happen in `dev` on main repo or in the `beta` branch only (I would guess `dev` before `beta` branch is made so that when it is made the image builds, yes?)

**Comment by stumpylog** [comment]
Questions are good so we can make the process at least somewhat better.

I think we could eliminate `main` here actually.  I was keeping `dev` just so the names match across the repos.  And the `main` in main will use a `builder@x.y.z` already, so there is never a need for `builder:main`

I think I would update the Dockerfile in the `beta-1.7.0` branch (at creation/before pushing).  That way you don't need to take the change to the `dev` branch back out.

**Comment by shamoon** [comment]
> Questions are good so we can make the process at least somewhat better.

Thanks for being patient =)

Yes that makes sense, branch to `beta`, make the dockerfile change and tag beta.

**Comment by qcasey** [comment]
> I think we could eliminate main here actually. I was keeping dev just so the names match across the repos. And the main in main will use a builder@x.y.z already, so there is never a need for builder:main

Does this mean we can delete the `builder:main` branch, and make `dev` the default here?

**Comment by stumpylog** [comment]
That's correct.

builder branch `dev` makes image tag `:dev` which is used as the base for paperlexx-ngx `dev` image.
builder tag x.y.z is used as the base for ngx-x.y.z (betas and release)

And if a bug in the beta is found which needs a base image update, my vote would be delete and recreate the tag to keep it simple mapping between the two.

**Comment by qcasey** [comment]
Great!

> And if a bug in the beta is found which needs a base image update, my vote would be delete and recreate the tag to keep it simple mapping between the two.

Perfect, keeps everything straightforward.

**Review by qcasey — APPROVED** [review]

**Comment by stumpylog** [comment]
It doesn't look like I can change the default branch here.  So when you can, lets change that to `dev`

**Comment by shamoon** [comment]
Ps. Do you want to delete `main`?

**Comment by stumpylog** [comment]
Yes, that too.  No reason to leave it around to be confusing.

**Comment by shamoon** [comment]
Looks like qcasey took care of it. Cool to see this in action, builds really are super fast.

Q: So like in gador’s barcode PR where he needed new dependencies in the base image, he ended up having to tag v1.0.3 here in order to even build the feature- branch image. Is that the recommended process? I guess I wonder about how someone could test out a base image change without necessarily making it the newest version here. In gador’s case it’s fine because we’re going to merge it into core but I can imagine others where it’s still just getting tested etc

**Comment by stumpylog** [comment]
That's what the new process solves, I hope.

Now, this repo rebuilds the `:dev` tag with any change to that branch.  Such as adding a new package.  Then our main repo uses `:dev` as its base (or will soon: paperless-ngx/paperless-ngx#666).  No need to tag anything until a release is getting prepped.

It's still a little more work, since there's the coordination between repos, but not too bad.

**Comment by shamoon** [comment]
Ok think I get it, so in order for them to test they just make a PR here with the changes (and feature image will include that after merge).

Also means that after our next release and we merge `main` —> `dev` we need to change the dockerfile to use `:dev` tag again. Nbd obviously but I will make a note, I think we should add a -dev tag to the version string in there too anyway, so nbd to do one more thing.

**Comment by stumpylog** [comment]
Yep, that sounds like the process.  Since most PRs won't probably add new packages, I don't think the overhead of a second PR will be too terrible.  Mostly, it's transparent unless a new package or specific library new update comes along.

**Comment by stumpylog** [comment]
Looks alright to me?  I see it pulling the `:dev` tag and `pikepdf` is [already installed](https://github.com/paperless-ngx/paperless-ngx/runs/5871459725?check_suite_focus=true#step:7:1069).

**Comment by qcasey** [comment]
Great! Just wanted to be sure :) nice job here

**Comment by stumpylog** [comment]
I've got some more ideas to speed it up, but the current state seems Ok.  The real test is when dependabot actually comes along, we'll find out if this works haha.

**Pull request merged**
